# Generated by Django 3.2 on 2022-06-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_convocatoria_convocatoria_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='nivel_academico',
            field=models.CharField(choices=[('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('titulado', 'Titulado'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], default='universitario', max_length=15),
        ),
        migrations.AlterField(
            model_name='academico',
            name='area_profesional',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='academico',
            name='nivel_ingles',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('nativo', 'Nativo')], default='basico', max_length=15),
        ),
    ]
