# Generated by Django 3.2 on 2022-06-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220614_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='convocatoria_descripcion',
            field=models.CharField(max_length=1000, null=True, verbose_name='descripcion Convocatoria'),
        ),
    ]
