# Generated by Django 3.2 on 2022-06-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_convocatoria_convocatoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academico',
            name='area_profesional',
            field=models.CharField(max_length=100),
        ),
    ]
